### ISSUE TITLE
Do you plan on updating your repo?

### ISSUE THREAD

**Issue by multinerd** [baoduy/HBD.Services#1]
I was hoping to peek at the source code for `HBD.Services.Email` and the nuget linked to this repo but i was unable to find the source code.

Also, thank you for open sourcing your projects. Its been a great boost in helping me learn better infrastructure.

**Comment by multinerd** [comment]
I think `hbd.framework` needs to be update too.

**Comment by baoduy** [comment]
Sure, i will update soon

**Comment by baoduy** [comment]
Hi @Multinerd the repo had been updated. Please take a look

**Comment by multinerd** [comment]
Thanks for updating. Huge projects like these help me understand better architecting

**Comment by baoduy** [comment]
I close the issue now. Please open the new one if any.
